"""Integration contracts for external Nuestra Casita systems."""

from casita.integrations.base import (
    AppliedChange,
    Capability,
    CapabilityData,
    DiagnosableIntegration,
    DiagnosticCheck,
    FieldDifference,
    HealthStatus,
    Integration,
    IntegrationDescriptor,
    IntegrationHealth,
    IntegrationSnapshot,
    IntegrationRuntime,
    PlannedChange,
    ReadRequest,
    RuntimeInspectableIntegration,
    SyncAction,
    SyncRequest,
    SynchronizationPlan,
    SynchronizationResult,
    SynchronizingIntegration,
)

__all__ = [
    "AppliedChange",
    "Capability",
    "CapabilityData",
    "DiagnosableIntegration",
    "DiagnosticCheck",
    "FieldDifference",
    "HealthStatus",
    "Integration",
    "IntegrationDescriptor",
    "IntegrationHealth",
    "IntegrationSnapshot",
    "IntegrationRuntime",
    "PlannedChange",
    "ReadRequest",
    "RuntimeInspectableIntegration",
    "SyncAction",
    "SyncRequest",
    "SynchronizationPlan",
    "SynchronizationResult",
    "SynchronizingIntegration",
]
