"""
Execution engine for Nuestra Casita synchronization plans.

This module applies product creation and update operations to Grocy.

Nothing in this module runs automatically. Changes are only sent to Grocy
when apply_plan() is called by an explicit --apply command.
"""

from typing import Any

from casita.grocy import post, put
from casita.lookups import build_lookups
from casita.payloads import (
    build_product_create_payload,
    build_product_update_payload,
)


def normalize_name(value: Any) -> str:
    """
    Convert a value into a clean display name.
    """

    if value is None:
        return "Unknown product"

    name = str(value).strip()

    if name == "":
        return "Unknown product"

    return name


def apply_product_create(
    item: dict[str, Any],
    lookups: dict[str, dict[Any, Any]],
) -> Any:
    """
    Create one product in Grocy.

    Args:
        item:
            One create item from the execution plan.

        lookups:
            Grocy lookup tables used to resolve product groups,
            locations, and quantity units.

    Returns:
        The response returned by the Grocy API client.

    Raises:
        ValueError:
            If the execution-plan item does not contain valid catalog data.
    """

    product_name = normalize_name(item.get("name"))
    catalog_product = item.get("catalog")

    if not isinstance(catalog_product, dict):
        raise ValueError(
            f"{product_name}: create plan item does not contain "
            "a valid catalog product."
        )

    payload = build_product_create_payload(
        catalog_product,
        lookups,
    )

    return post(
        "/objects/products",
        payload,
    )


def apply_product_update(
    item: dict[str, Any],
) -> Any:
    """
    Update one existing product in Grocy.

    Args:
        item:
            One update item from the execution plan.

    Returns:
        The response returned by the Grocy API client.

    Raises:
        ValueError:
            If the product ID is missing or invalid.
    """

    product_name = normalize_name(item.get("name"))
    product_id = item.get("product_id")

    if product_id is None:
        raise ValueError(
            f"{product_name}: update plan item is missing product_id."
        )

    try:
        product_id = int(product_id)
    except (TypeError, ValueError) as error:
        raise ValueError(
            f"{product_name}: invalid product_id {product_id!r}."
        ) from error

    payload = build_product_update_payload(item)

    return put(
        f"/objects/products/{product_id}",
        payload,
    )


def apply_creates(
    create_items: list[dict[str, Any]],
    lookups: dict[str, dict[Any, Any]],
) -> int:
    """
    Apply every product creation operation.

    Returns:
        The number of products successfully created.
    """

    created_count = 0

    for item in create_items:
        product_name = normalize_name(item.get("name"))

        print(f"+ CREATE    {product_name}")

        try:
            apply_product_create(
                item,
                lookups,
            )
        except Exception as error:
            print(f"    FAILED: {error}")
            raise

        created_count += 1
        print("    Created successfully.")
        print()

    return created_count


def apply_updates(
    update_items: list[dict[str, Any]],
) -> int:
    """
    Apply every product update operation.

    Returns:
        The number of products successfully updated.
    """

    updated_count = 0

    for item in update_items:
        product_name = normalize_name(item.get("name"))

        print(f"~ UPDATE    {product_name}")

        try:
            apply_product_update(item)
        except Exception as error:
            print(f"    FAILED: {error}")
            raise

        updated_count += 1
        print("    Updated successfully.")
        print()

    return updated_count


def apply_plan(
    plan: dict[str, Any],
) -> dict[str, int]:
    """
    Apply a complete product synchronization plan.

    The plan is expected to contain these lists:

        match
        update
        create

    Matching products require no action.

    Missing products are created with:

        POST /api/objects/products

    Changed products are updated with:

        PUT /api/objects/products/{product_id}

    Args:
        plan:
            Execution plan generated by sync_products().

    Returns:
        A summary dictionary containing:

            created
            updated
            matched

    Raises:
        ValueError:
            If the execution plan is invalid.

        Exception:
            Any payload-building or Grocy API error is printed and
            re-raised. Processing stops immediately so a failed operation
            cannot be mistaken for a successful synchronization.
    """

    if not isinstance(plan, dict):
        raise ValueError(
            "The execution plan must be a dictionary."
        )

    create_items = plan.get("create", [])
    update_items = plan.get("update", [])
    match_items = plan.get("match", [])

    if not isinstance(create_items, list):
        raise ValueError(
            "Execution plan 'create' must be a list."
        )

    if not isinstance(update_items, list):
        raise ValueError(
            "Execution plan 'update' must be a list."
        )

    if not isinstance(match_items, list):
        raise ValueError(
            "Execution plan 'match' must be a list."
        )

    print()
    print("=" * 40)
    print("Applying Plan")
    print("=" * 40)
    print()

    print(f"{len(create_items)} products to create")
    print(f"{len(update_items)} products to update")
    print()

    if not create_items and not update_items:
        return {
            "created": 0,
            "updated": 0,
            "matched": len(match_items),
        }

    lookups: dict[str, dict[Any, Any]] = {}

    if create_items:
        print("Loading lookup tables for product creation...")
        lookups = build_lookups()
        print("Lookup tables loaded.")
        print()

    created_count = apply_creates(
        create_items,
        lookups,
    )

    updated_count = apply_updates(
        update_items,
    )

    print("=" * 40)
    print("Apply Summary")
    print("=" * 40)
    print()
    print(f"Matched: {len(match_items)}")
    print(f"Created: {created_count}")
    print(f"Updated: {updated_count}")

    return {
        "created": created_count,
        "updated": updated_count,
        "matched": len(match_items),
    }
